package de.tudarmstadt.informatik.tk.kraken.android.sdk.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.PositionSensor;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.GyroscopeSensor;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.AccelerometerSensor;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.MagneticFieldSensor;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.MotionActivityEvent;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.ConnectionEvent;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.WifiConnectionEvent;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.MobileConnectionEvent;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.LoudnessEvent;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.MagneticFieldUncalibratedSensor;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.MagneticFieldUncalibratedSensor;

import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.PositionSensorDao;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.GyroscopeSensorDao;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.AccelerometerSensorDao;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.MagneticFieldSensorDao;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.MotionActivityEventDao;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.ConnectionEventDao;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.WifiConnectionEventDao;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.MobileConnectionEventDao;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.LoudnessEventDao;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.MagneticFieldUncalibratedSensorDao;
import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.MagneticFieldUncalibratedSensorDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig positionSensorDaoConfig;
    private final DaoConfig gyroscopeSensorDaoConfig;
    private final DaoConfig accelerometerSensorDaoConfig;
    private final DaoConfig magneticFieldSensorDaoConfig;
    private final DaoConfig motionActivityEventDaoConfig;
    private final DaoConfig connectionEventDaoConfig;
    private final DaoConfig wifiConnectionEventDaoConfig;
    private final DaoConfig mobileConnectionEventDaoConfig;
    private final DaoConfig loudnessEventDaoConfig;
    private final DaoConfig magneticFieldUncalibratedSensorDaoConfig;
    private final DaoConfig magneticFieldUncalibratedSensorDaoConfig;

    private final PositionSensorDao positionSensorDao;
    private final GyroscopeSensorDao gyroscopeSensorDao;
    private final AccelerometerSensorDao accelerometerSensorDao;
    private final MagneticFieldSensorDao magneticFieldSensorDao;
    private final MotionActivityEventDao motionActivityEventDao;
    private final ConnectionEventDao connectionEventDao;
    private final WifiConnectionEventDao wifiConnectionEventDao;
    private final MobileConnectionEventDao mobileConnectionEventDao;
    private final LoudnessEventDao loudnessEventDao;
    private final MagneticFieldUncalibratedSensorDao magneticFieldUncalibratedSensorDao;
    private final MagneticFieldUncalibratedSensorDao magneticFieldUncalibratedSensorDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        positionSensorDaoConfig = daoConfigMap.get(PositionSensorDao.class).clone();
        positionSensorDaoConfig.initIdentityScope(type);

        gyroscopeSensorDaoConfig = daoConfigMap.get(GyroscopeSensorDao.class).clone();
        gyroscopeSensorDaoConfig.initIdentityScope(type);

        accelerometerSensorDaoConfig = daoConfigMap.get(AccelerometerSensorDao.class).clone();
        accelerometerSensorDaoConfig.initIdentityScope(type);

        magneticFieldSensorDaoConfig = daoConfigMap.get(MagneticFieldSensorDao.class).clone();
        magneticFieldSensorDaoConfig.initIdentityScope(type);

        motionActivityEventDaoConfig = daoConfigMap.get(MotionActivityEventDao.class).clone();
        motionActivityEventDaoConfig.initIdentityScope(type);

        connectionEventDaoConfig = daoConfigMap.get(ConnectionEventDao.class).clone();
        connectionEventDaoConfig.initIdentityScope(type);

        wifiConnectionEventDaoConfig = daoConfigMap.get(WifiConnectionEventDao.class).clone();
        wifiConnectionEventDaoConfig.initIdentityScope(type);

        mobileConnectionEventDaoConfig = daoConfigMap.get(MobileConnectionEventDao.class).clone();
        mobileConnectionEventDaoConfig.initIdentityScope(type);

        loudnessEventDaoConfig = daoConfigMap.get(LoudnessEventDao.class).clone();
        loudnessEventDaoConfig.initIdentityScope(type);

        magneticFieldUncalibratedSensorDaoConfig = daoConfigMap.get(MagneticFieldUncalibratedSensorDao.class).clone();
        magneticFieldUncalibratedSensorDaoConfig.initIdentityScope(type);

        magneticFieldUncalibratedSensorDaoConfig = daoConfigMap.get(MagneticFieldUncalibratedSensorDao.class).clone();
        magneticFieldUncalibratedSensorDaoConfig.initIdentityScope(type);

        positionSensorDao = new PositionSensorDao(positionSensorDaoConfig, this);
        gyroscopeSensorDao = new GyroscopeSensorDao(gyroscopeSensorDaoConfig, this);
        accelerometerSensorDao = new AccelerometerSensorDao(accelerometerSensorDaoConfig, this);
        magneticFieldSensorDao = new MagneticFieldSensorDao(magneticFieldSensorDaoConfig, this);
        motionActivityEventDao = new MotionActivityEventDao(motionActivityEventDaoConfig, this);
        connectionEventDao = new ConnectionEventDao(connectionEventDaoConfig, this);
        wifiConnectionEventDao = new WifiConnectionEventDao(wifiConnectionEventDaoConfig, this);
        mobileConnectionEventDao = new MobileConnectionEventDao(mobileConnectionEventDaoConfig, this);
        loudnessEventDao = new LoudnessEventDao(loudnessEventDaoConfig, this);
        magneticFieldUncalibratedSensorDao = new MagneticFieldUncalibratedSensorDao(magneticFieldUncalibratedSensorDaoConfig, this);
        magneticFieldUncalibratedSensorDao = new MagneticFieldUncalibratedSensorDao(magneticFieldUncalibratedSensorDaoConfig, this);

        registerDao(PositionSensor.class, positionSensorDao);
        registerDao(GyroscopeSensor.class, gyroscopeSensorDao);
        registerDao(AccelerometerSensor.class, accelerometerSensorDao);
        registerDao(MagneticFieldSensor.class, magneticFieldSensorDao);
        registerDao(MotionActivityEvent.class, motionActivityEventDao);
        registerDao(ConnectionEvent.class, connectionEventDao);
        registerDao(WifiConnectionEvent.class, wifiConnectionEventDao);
        registerDao(MobileConnectionEvent.class, mobileConnectionEventDao);
        registerDao(LoudnessEvent.class, loudnessEventDao);
        registerDao(MagneticFieldUncalibratedSensor.class, magneticFieldUncalibratedSensorDao);
        registerDao(MagneticFieldUncalibratedSensor.class, magneticFieldUncalibratedSensorDao);
    }
    
    public void clear() {
        positionSensorDaoConfig.getIdentityScope().clear();
        gyroscopeSensorDaoConfig.getIdentityScope().clear();
        accelerometerSensorDaoConfig.getIdentityScope().clear();
        magneticFieldSensorDaoConfig.getIdentityScope().clear();
        motionActivityEventDaoConfig.getIdentityScope().clear();
        connectionEventDaoConfig.getIdentityScope().clear();
        wifiConnectionEventDaoConfig.getIdentityScope().clear();
        mobileConnectionEventDaoConfig.getIdentityScope().clear();
        loudnessEventDaoConfig.getIdentityScope().clear();
        magneticFieldUncalibratedSensorDaoConfig.getIdentityScope().clear();
        magneticFieldUncalibratedSensorDaoConfig.getIdentityScope().clear();
    }

    public PositionSensorDao getPositionSensorDao() {
        return positionSensorDao;
    }

    public GyroscopeSensorDao getGyroscopeSensorDao() {
        return gyroscopeSensorDao;
    }

    public AccelerometerSensorDao getAccelerometerSensorDao() {
        return accelerometerSensorDao;
    }

    public MagneticFieldSensorDao getMagneticFieldSensorDao() {
        return magneticFieldSensorDao;
    }

    public MotionActivityEventDao getMotionActivityEventDao() {
        return motionActivityEventDao;
    }

    public ConnectionEventDao getConnectionEventDao() {
        return connectionEventDao;
    }

    public WifiConnectionEventDao getWifiConnectionEventDao() {
        return wifiConnectionEventDao;
    }

    public MobileConnectionEventDao getMobileConnectionEventDao() {
        return mobileConnectionEventDao;
    }

    public LoudnessEventDao getLoudnessEventDao() {
        return loudnessEventDao;
    }

    public MagneticFieldUncalibratedSensorDao getMagneticFieldUncalibratedSensorDao() {
        return magneticFieldUncalibratedSensorDao;
    }

    public MagneticFieldUncalibratedSensorDao getMagneticFieldUncalibratedSensorDao() {
        return magneticFieldUncalibratedSensorDao;
    }

}
