package de.tudarmstadt.informatik.tk.kraken.android.sdk.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SENSOR_BROWSER_HISTORY".
 */
public class SensorBrowserHistory implements de.tudarmstadt.informatik.tk.kraken.android.sdk.interfaces.IDbUpdatableSensor {

    private Long id;
    private Long historyId;
    private String url;
    private String title;
    private Long lastVisited;
    private Integer visits;
    private Boolean bookmark;
    private Long timestamp;
    private Boolean isNew;
    private Boolean isUpdated;
    private Boolean isDeleted;

    public SensorBrowserHistory() {
    }

    public SensorBrowserHistory(Long id) {
        this.id = id;
    }

    public SensorBrowserHistory(Long id, Long historyId, String url, String title, Long lastVisited, Integer visits, Boolean bookmark, Long timestamp, Boolean isNew, Boolean isUpdated, Boolean isDeleted) {
        this.id = id;
        this.historyId = historyId;
        this.url = url;
        this.title = title;
        this.lastVisited = lastVisited;
        this.visits = visits;
        this.bookmark = bookmark;
        this.timestamp = timestamp;
        this.isNew = isNew;
        this.isUpdated = isUpdated;
        this.isDeleted = isDeleted;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getHistoryId() {
        return historyId;
    }

    public void setHistoryId(Long historyId) {
        this.historyId = historyId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getLastVisited() {
        return lastVisited;
    }

    public void setLastVisited(Long lastVisited) {
        this.lastVisited = lastVisited;
    }

    public Integer getVisits() {
        return visits;
    }

    public void setVisits(Integer visits) {
        this.visits = visits;
    }

    public Boolean getBookmark() {
        return bookmark;
    }

    public void setBookmark(Boolean bookmark) {
        this.bookmark = bookmark;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public Boolean getIsNew() {
        return isNew;
    }

    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    public Boolean getIsUpdated() {
        return isUpdated;
    }

    public void setIsUpdated(Boolean isUpdated) {
        this.isUpdated = isUpdated;
    }

    public Boolean getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

}
