package de.tudarmstadt.informatik.tk.android.kraken.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.tudarmstadt.informatik.tk.android.kraken.db.DbRunningTasksEvent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "running_tasks_event".
*/
public class DbRunningTasksEventDao extends AbstractDao<DbRunningTasksEvent, Long> {

    public static final String TABLENAME = "running_tasks_event";

    /**
     * Properties of entity DbRunningTasksEvent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RunningTasks = new Property(1, String.class, "runningTasks", false, "RUNNING_TASKS");
        public final static Property StackPosition = new Property(2, Integer.class, "stackPosition", false, "STACK_POSITION");
        public final static Property Created = new Property(3, String.class, "created", false, "CREATED");
    };


    public DbRunningTasksEventDao(DaoConfig config) {
        super(config);
    }
    
    public DbRunningTasksEventDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"running_tasks_event\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"RUNNING_TASKS\" TEXT," + // 1: runningTasks
                "\"STACK_POSITION\" INTEGER," + // 2: stackPosition
                "\"CREATED\" TEXT NOT NULL );"); // 3: created
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_running_tasks_event__id ON running_tasks_event" +
                " (\"_id\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"running_tasks_event\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbRunningTasksEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String runningTasks = entity.getRunningTasks();
        if (runningTasks != null) {
            stmt.bindString(2, runningTasks);
        }
 
        Integer stackPosition = entity.getStackPosition();
        if (stackPosition != null) {
            stmt.bindLong(3, stackPosition);
        }
        stmt.bindString(4, entity.getCreated());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbRunningTasksEvent readEntity(Cursor cursor, int offset) {
        DbRunningTasksEvent entity = new DbRunningTasksEvent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // runningTasks
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // stackPosition
            cursor.getString(offset + 3) // created
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbRunningTasksEvent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRunningTasks(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStackPosition(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCreated(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbRunningTasksEvent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbRunningTasksEvent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
