package de.tudarmstadt.informatik.tk.assistance.sdk.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "browser_history_sensor".
*/
public class DbBrowserHistorySensorDao extends AbstractDao<DbBrowserHistorySensor, Long> {

    public static final String TABLENAME = "browser_history_sensor";

    /**
     * Properties of entity DbBrowserHistorySensor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public static final Property Id = new Property(0, Long.class, "id", true, "_id");
        public static final Property Url = new Property(1, String.class, "url", false, "URL");
        public static final Property Title = new Property(2, String.class, "title", false, "TITLE");
        public static final Property LastVisited = new Property(3, Long.class, "lastVisited", false, "LAST_VISITED");
        public static final Property Visits = new Property(4, Integer.class, "visits", false, "VISITS");
        public static final Property Bookmark = new Property(5, Boolean.class, "bookmark", false, "BOOKMARK");
        public static final Property IsNew = new Property(6, Boolean.class, "isNew", false, "IS_NEW");
        public static final Property IsUpdated = new Property(7, Boolean.class, "isUpdated", false, "IS_UPDATED");
        public static final Property IsDeleted = new Property(8, Boolean.class, "isDeleted", false, "IS_DELETED");
        public static final Property Created = new Property(9, String.class, "created", false, "CREATED");
        public static final Property DeviceId = new Property(10, Long.class, "deviceId", false, "DEVICE_ID");
    }

    private DaoSession daoSession;


    public DbBrowserHistorySensorDao(DaoConfig config) {
        super(config);
    }
    
    public DbBrowserHistorySensorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"browser_history_sensor\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"URL\" TEXT," + // 1: url
                "\"TITLE\" TEXT," + // 2: title
                "\"LAST_VISITED\" INTEGER," + // 3: lastVisited
                "\"VISITS\" INTEGER," + // 4: visits
                "\"BOOKMARK\" INTEGER," + // 5: bookmark
                "\"IS_NEW\" INTEGER," + // 6: isNew
                "\"IS_UPDATED\" INTEGER," + // 7: isUpdated
                "\"IS_DELETED\" INTEGER," + // 8: isDeleted
                "\"CREATED\" TEXT NOT NULL ," + // 9: created
                "\"DEVICE_ID\" INTEGER);"); // 10: deviceId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_browser_history_sensor__id ON browser_history_sensor" +
                " (\"_id\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_browser_history_sensor_DEVICE_ID ON browser_history_sensor" +
                " (\"DEVICE_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"browser_history_sensor\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbBrowserHistorySensor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        Long lastVisited = entity.getLastVisited();
        if (lastVisited != null) {
            stmt.bindLong(4, lastVisited);
        }
 
        Integer visits = entity.getVisits();
        if (visits != null) {
            stmt.bindLong(5, visits);
        }
 
        Boolean bookmark = entity.getBookmark();
        if (bookmark != null) {
            stmt.bindLong(6, bookmark ? 1L: 0L);
        }
 
        Boolean isNew = entity.getIsNew();
        if (isNew != null) {
            stmt.bindLong(7, isNew ? 1L: 0L);
        }
 
        Boolean isUpdated = entity.getIsUpdated();
        if (isUpdated != null) {
            stmt.bindLong(8, isUpdated ? 1L: 0L);
        }
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(9, isDeleted ? 1L: 0L);
        }
        stmt.bindString(10, entity.getCreated());
 
        Long deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindLong(11, deviceId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbBrowserHistorySensor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        Long lastVisited = entity.getLastVisited();
        if (lastVisited != null) {
            stmt.bindLong(4, lastVisited);
        }
 
        Integer visits = entity.getVisits();
        if (visits != null) {
            stmt.bindLong(5, visits);
        }
 
        Boolean bookmark = entity.getBookmark();
        if (bookmark != null) {
            stmt.bindLong(6, bookmark ? 1L: 0L);
        }
 
        Boolean isNew = entity.getIsNew();
        if (isNew != null) {
            stmt.bindLong(7, isNew ? 1L: 0L);
        }
 
        Boolean isUpdated = entity.getIsUpdated();
        if (isUpdated != null) {
            stmt.bindLong(8, isUpdated ? 1L: 0L);
        }
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(9, isDeleted ? 1L: 0L);
        }
        stmt.bindString(10, entity.getCreated());
 
        Long deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindLong(11, deviceId);
        }
    }

    @Override
    protected final void attachEntity(DbBrowserHistorySensor entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbBrowserHistorySensor readEntity(Cursor cursor, int offset) {
        DbBrowserHistorySensor entity = new DbBrowserHistorySensor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // url
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // lastVisited
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // visits
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // bookmark
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // isNew
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // isUpdated
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // isDeleted
            cursor.getString(offset + 9), // created
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10) // deviceId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbBrowserHistorySensor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLastVisited(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setVisits(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setBookmark(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setIsNew(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setIsUpdated(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setIsDeleted(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setCreated(cursor.getString(offset + 9));
        entity.setDeviceId(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbBrowserHistorySensor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbBrowserHistorySensor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbBrowserHistorySensor entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbDeviceDao().getAllColumns());
            builder.append(" FROM browser_history_sensor T");
            builder.append(" LEFT JOIN device T0 ON T.\"DEVICE_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbBrowserHistorySensor loadCurrentDeep(Cursor cursor, boolean lock) {
        DbBrowserHistorySensor entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbDevice dbDevice = loadCurrentOther(daoSession.getDbDeviceDao(), cursor, offset);
        entity.setDbDevice(dbDevice);

        return entity;    
    }

    public DbBrowserHistorySensor loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            }
            if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbBrowserHistorySensor> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbBrowserHistorySensor> list = new ArrayList<>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbBrowserHistorySensor> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbBrowserHistorySensor> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
