package de.tudarmstadt.informatik.tk.assistance.sdk.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "contact_number_sensor".
*/
public class DbContactNumberSensorDao extends AbstractDao<DbContactNumberSensor, Long> {

    public static final String TABLENAME = "contact_number_sensor";

    /**
     * Properties of entity DbContactNumberSensor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public static final Property Id = new Property(0, Long.class, "id", true, "_id");
        public static final Property NumberId = new Property(1, long.class, "numberId", false, "NUMBER_ID");
        public static final Property Type = new Property(2, String.class, "type", false, "TYPE");
        public static final Property Number = new Property(3, String.class, "number", false, "NUMBER");
        public static final Property IsNew = new Property(4, Boolean.class, "isNew", false, "IS_NEW");
        public static final Property IsUpdated = new Property(5, Boolean.class, "isUpdated", false, "IS_UPDATED");
        public static final Property IsDeleted = new Property(6, Boolean.class, "isDeleted", false, "IS_DELETED");
        public static final Property Created = new Property(7, String.class, "created", false, "CREATED");
        public static final Property ContactId = new Property(8, long.class, "contactId", false, "CONTACT_ID");
        public static final Property DeviceId = new Property(9, Long.class, "deviceId", false, "DEVICE_ID");
    }

    private DaoSession daoSession;

    private Query<DbContactNumberSensor> dbContactSensor_DbContactNumberSensorListQuery;

    public DbContactNumberSensorDao(DaoConfig config) {
        super(config);
    }
    
    public DbContactNumberSensorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"contact_number_sensor\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NUMBER_ID\" INTEGER NOT NULL UNIQUE ," + // 1: numberId
                "\"TYPE\" TEXT," + // 2: type
                "\"NUMBER\" TEXT," + // 3: number
                "\"IS_NEW\" INTEGER," + // 4: isNew
                "\"IS_UPDATED\" INTEGER," + // 5: isUpdated
                "\"IS_DELETED\" INTEGER," + // 6: isDeleted
                "\"CREATED\" TEXT NOT NULL ," + // 7: created
                "\"CONTACT_ID\" INTEGER NOT NULL ," + // 8: contactId
                "\"DEVICE_ID\" INTEGER);"); // 9: deviceId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_contact_number_sensor__id ON contact_number_sensor" +
                " (\"_id\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_contact_number_sensor_CONTACT_ID ON contact_number_sensor" +
                " (\"CONTACT_ID\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_contact_number_sensor_DEVICE_ID ON contact_number_sensor" +
                " (\"DEVICE_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"contact_number_sensor\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbContactNumberSensor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNumberId());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(4, number);
        }
 
        Boolean isNew = entity.getIsNew();
        if (isNew != null) {
            stmt.bindLong(5, isNew ? 1L: 0L);
        }
 
        Boolean isUpdated = entity.getIsUpdated();
        if (isUpdated != null) {
            stmt.bindLong(6, isUpdated ? 1L: 0L);
        }
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(7, isDeleted ? 1L: 0L);
        }
        stmt.bindString(8, entity.getCreated());
        stmt.bindLong(9, entity.getContactId());
 
        Long deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindLong(10, deviceId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbContactNumberSensor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNumberId());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(4, number);
        }
 
        Boolean isNew = entity.getIsNew();
        if (isNew != null) {
            stmt.bindLong(5, isNew ? 1L: 0L);
        }
 
        Boolean isUpdated = entity.getIsUpdated();
        if (isUpdated != null) {
            stmt.bindLong(6, isUpdated ? 1L: 0L);
        }
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(7, isDeleted ? 1L: 0L);
        }
        stmt.bindString(8, entity.getCreated());
        stmt.bindLong(9, entity.getContactId());
 
        Long deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindLong(10, deviceId);
        }
    }

    @Override
    protected final void attachEntity(DbContactNumberSensor entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbContactNumberSensor readEntity(Cursor cursor, int offset) {
        DbContactNumberSensor entity = new DbContactNumberSensor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // numberId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // number
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // isNew
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // isUpdated
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // isDeleted
            cursor.getString(offset + 7), // created
            cursor.getLong(offset + 8), // contactId
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9) // deviceId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbContactNumberSensor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNumberId(cursor.getLong(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNumber(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsNew(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setIsUpdated(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setIsDeleted(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setCreated(cursor.getString(offset + 7));
        entity.setContactId(cursor.getLong(offset + 8));
        entity.setDeviceId(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbContactNumberSensor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbContactNumberSensor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbContactNumberSensor entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dbContactNumberSensorList" to-many relationship of DbContactSensor. */
    public List<DbContactNumberSensor> _queryDbContactSensor_DbContactNumberSensorList(long contactId) {
        synchronized (this) {
            if (dbContactSensor_DbContactNumberSensorListQuery == null) {
                QueryBuilder<DbContactNumberSensor> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ContactId.eq(null));
                dbContactSensor_DbContactNumberSensorListQuery = queryBuilder.build();
            }
        }
        Query<DbContactNumberSensor> query = dbContactSensor_DbContactNumberSensorListQuery.forCurrentThread();
        query.setParameter(0, contactId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbContactSensorDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getDbDeviceDao().getAllColumns());
            builder.append(" FROM contact_number_sensor T");
            builder.append(" LEFT JOIN contact_sensor T0 ON T.\"CONTACT_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN device T1 ON T.\"DEVICE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbContactNumberSensor loadCurrentDeep(Cursor cursor, boolean lock) {
        DbContactNumberSensor entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbContactSensor dbContactSensor = loadCurrentOther(daoSession.getDbContactSensorDao(), cursor, offset);
         if(dbContactSensor != null) {
            entity.setDbContactSensor(dbContactSensor);
        }
        offset += daoSession.getDbContactSensorDao().getAllColumns().length;

        DbDevice dbDevice = loadCurrentOther(daoSession.getDbDeviceDao(), cursor, offset);
        entity.setDbDevice(dbDevice);

        return entity;    
    }

    public DbContactNumberSensor loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            }
            if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbContactNumberSensor> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbContactNumberSensor> list = new ArrayList<>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbContactNumberSensor> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbContactNumberSensor> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
