package de.tudarmstadt.informatik.tk.assistance.sdk.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "facebook_sensor".
*/
public class DbFacebookSensorDao extends AbstractDao<DbFacebookSensor, Long> {

    public static final String TABLENAME = "facebook_sensor";

    /**
     * Properties of entity DbFacebookSensor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OauthToken = new Property(1, String.class, "oauthToken", false, "OAUTH_TOKEN");
        public final static Property PermissionsDeclined = new Property(2, String.class, "permissionsDeclined", false, "PERMISSIONS_DECLINED");
        public final static Property Permissions = new Property(3, String.class, "permissions", false, "PERMISSIONS");
        public final static Property WasChanged = new Property(4, boolean.class, "wasChanged", false, "WAS_CHANGED");
        public final static Property Created = new Property(5, String.class, "created", false, "CREATED");
        public final static Property UserId = new Property(6, Long.class, "userId", false, "USER_ID");
    }

    private DaoSession daoSession;


    public DbFacebookSensorDao(DaoConfig config) {
        super(config);
    }
    
    public DbFacebookSensorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"facebook_sensor\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"OAUTH_TOKEN\" TEXT," + // 1: oauthToken
                "\"PERMISSIONS_DECLINED\" TEXT," + // 2: permissionsDeclined
                "\"PERMISSIONS\" TEXT," + // 3: permissions
                "\"WAS_CHANGED\" INTEGER NOT NULL ," + // 4: wasChanged
                "\"CREATED\" TEXT NOT NULL ," + // 5: created
                "\"USER_ID\" INTEGER);"); // 6: userId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_facebook_sensor__id ON facebook_sensor" +
                " (\"_id\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_facebook_sensor_USER_ID ON facebook_sensor" +
                " (\"USER_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"facebook_sensor\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbFacebookSensor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String oauthToken = entity.getOauthToken();
        if (oauthToken != null) {
            stmt.bindString(2, oauthToken);
        }
 
        String permissionsDeclined = entity.getPermissionsDeclined();
        if (permissionsDeclined != null) {
            stmt.bindString(3, permissionsDeclined);
        }
 
        String permissions = entity.getPermissions();
        if (permissions != null) {
            stmt.bindString(4, permissions);
        }
        stmt.bindLong(5, entity.getWasChanged() ? 1L: 0L);
        stmt.bindString(6, entity.getCreated());
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(7, userId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbFacebookSensor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String oauthToken = entity.getOauthToken();
        if (oauthToken != null) {
            stmt.bindString(2, oauthToken);
        }
 
        String permissionsDeclined = entity.getPermissionsDeclined();
        if (permissionsDeclined != null) {
            stmt.bindString(3, permissionsDeclined);
        }
 
        String permissions = entity.getPermissions();
        if (permissions != null) {
            stmt.bindString(4, permissions);
        }
        stmt.bindLong(5, entity.getWasChanged() ? 1L: 0L);
        stmt.bindString(6, entity.getCreated());
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(7, userId);
        }
    }

    @Override
    protected final void attachEntity(DbFacebookSensor entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbFacebookSensor readEntity(Cursor cursor, int offset) {
        DbFacebookSensor entity = new DbFacebookSensor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // oauthToken
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // permissionsDeclined
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // permissions
            cursor.getShort(offset + 4) != 0, // wasChanged
            cursor.getString(offset + 5), // created
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // userId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbFacebookSensor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOauthToken(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPermissionsDeclined(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPermissions(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWasChanged(cursor.getShort(offset + 4) != 0);
        entity.setCreated(cursor.getString(offset + 5));
        entity.setUserId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbFacebookSensor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbFacebookSensor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbFacebookSensor entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbUserDao().getAllColumns());
            builder.append(" FROM facebook_sensor T");
            builder.append(" LEFT JOIN user T0 ON T.\"USER_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbFacebookSensor loadCurrentDeep(Cursor cursor, boolean lock) {
        DbFacebookSensor entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbUser dbUser = loadCurrentOther(daoSession.getDbUserDao(), cursor, offset);
        entity.setDbUser(dbUser);

        return entity;    
    }

    public DbFacebookSensor loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbFacebookSensor> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbFacebookSensor> list = new ArrayList<DbFacebookSensor>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbFacebookSensor> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbFacebookSensor> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
