package de.tudarmstadt.informatik.tk.assistance.sdk.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "mobile_connection_sensor".
*/
public class DbMobileConnectionSensorDao extends AbstractDao<DbMobileConnectionSensor, Long> {

    public static final String TABLENAME = "mobile_connection_sensor";

    /**
     * Properties of entity DbMobileConnectionSensor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CarrierName = new Property(1, String.class, "carrierName", false, "CARRIER_NAME");
        public final static Property MobileCountryCode = new Property(2, String.class, "mobileCountryCode", false, "MOBILE_COUNTRY_CODE");
        public final static Property MobileNetworkCode = new Property(3, String.class, "mobileNetworkCode", false, "MOBILE_NETWORK_CODE");
        public final static Property Created = new Property(4, String.class, "created", false, "CREATED");
        public final static Property VoipAvailable = new Property(5, Boolean.class, "voipAvailable", false, "VOIP_AVAILABLE");
        public final static Property DeviceId = new Property(6, Long.class, "deviceId", false, "DEVICE_ID");
    };

    private DaoSession daoSession;


    public DbMobileConnectionSensorDao(DaoConfig config) {
        super(config);
    }
    
    public DbMobileConnectionSensorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"mobile_connection_sensor\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CARRIER_NAME\" TEXT," + // 1: carrierName
                "\"MOBILE_COUNTRY_CODE\" TEXT," + // 2: mobileCountryCode
                "\"MOBILE_NETWORK_CODE\" TEXT," + // 3: mobileNetworkCode
                "\"CREATED\" TEXT NOT NULL ," + // 4: created
                "\"VOIP_AVAILABLE\" INTEGER," + // 5: voipAvailable
                "\"DEVICE_ID\" INTEGER);"); // 6: deviceId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_mobile_connection_sensor__id ON mobile_connection_sensor" +
                " (\"_id\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_mobile_connection_sensor_DEVICE_ID ON mobile_connection_sensor" +
                " (\"DEVICE_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"mobile_connection_sensor\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbMobileConnectionSensor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String carrierName = entity.getCarrierName();
        if (carrierName != null) {
            stmt.bindString(2, carrierName);
        }
 
        String mobileCountryCode = entity.getMobileCountryCode();
        if (mobileCountryCode != null) {
            stmt.bindString(3, mobileCountryCode);
        }
 
        String mobileNetworkCode = entity.getMobileNetworkCode();
        if (mobileNetworkCode != null) {
            stmt.bindString(4, mobileNetworkCode);
        }
        stmt.bindString(5, entity.getCreated());
 
        Boolean voipAvailable = entity.getVoipAvailable();
        if (voipAvailable != null) {
            stmt.bindLong(6, voipAvailable ? 1L: 0L);
        }
 
        Long deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindLong(7, deviceId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbMobileConnectionSensor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String carrierName = entity.getCarrierName();
        if (carrierName != null) {
            stmt.bindString(2, carrierName);
        }
 
        String mobileCountryCode = entity.getMobileCountryCode();
        if (mobileCountryCode != null) {
            stmt.bindString(3, mobileCountryCode);
        }
 
        String mobileNetworkCode = entity.getMobileNetworkCode();
        if (mobileNetworkCode != null) {
            stmt.bindString(4, mobileNetworkCode);
        }
        stmt.bindString(5, entity.getCreated());
 
        Boolean voipAvailable = entity.getVoipAvailable();
        if (voipAvailable != null) {
            stmt.bindLong(6, voipAvailable ? 1L: 0L);
        }
 
        Long deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindLong(7, deviceId);
        }
    }

    @Override
    protected final void attachEntity(DbMobileConnectionSensor entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbMobileConnectionSensor readEntity(Cursor cursor, int offset) {
        DbMobileConnectionSensor entity = new DbMobileConnectionSensor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // carrierName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mobileCountryCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mobileNetworkCode
            cursor.getString(offset + 4), // created
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // voipAvailable
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // deviceId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbMobileConnectionSensor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCarrierName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMobileCountryCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMobileNetworkCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCreated(cursor.getString(offset + 4));
        entity.setVoipAvailable(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setDeviceId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbMobileConnectionSensor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbMobileConnectionSensor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbDeviceDao().getAllColumns());
            builder.append(" FROM mobile_connection_sensor T");
            builder.append(" LEFT JOIN device T0 ON T.\"DEVICE_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbMobileConnectionSensor loadCurrentDeep(Cursor cursor, boolean lock) {
        DbMobileConnectionSensor entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbDevice dbDevice = loadCurrentOther(daoSession.getDbDeviceDao(), cursor, offset);
        entity.setDbDevice(dbDevice);

        return entity;    
    }

    public DbMobileConnectionSensor loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbMobileConnectionSensor> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbMobileConnectionSensor> list = new ArrayList<DbMobileConnectionSensor>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbMobileConnectionSensor> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbMobileConnectionSensor> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
