package de.tudarmstadt.informatik.tk.android.kraken.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "connection_event".
 */
public class ConnectionEvent implements de.tudarmstadt.informatik.tk.android.kraken.interfaces.IDbSensor {

    private long id;
    private Boolean isWifi;
    private Boolean isMobile;
    /** Not-null value. */
    private String created;

    public ConnectionEvent() {
    }

    public ConnectionEvent(long id) {
        this.id = id;
    }

    public ConnectionEvent(long id, Boolean isWifi, Boolean isMobile, String created) {
        this.id = id;
        this.isWifi = isWifi;
        this.isMobile = isMobile;
        this.created = created;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Boolean getIsWifi() {
        return isWifi;
    }

    public void setIsWifi(Boolean isWifi) {
        this.isWifi = isWifi;
    }

    public Boolean getIsMobile() {
        return isMobile;
    }

    public void setIsMobile(Boolean isMobile) {
        this.isMobile = isMobile;
    }

    /** Not-null value. */
    public String getCreated() {
        return created;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated(String created) {
        this.created = created;
    }

}
