package de.tudarmstadt.informatik.tk.android.kraken.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.tudarmstadt.informatik.tk.android.kraken.db.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "user".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "user";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Firstname = new Property(1, String.class, "firstname", false, "FIRSTNAME");
        public final static Property Lastname = new Property(2, String.class, "lastname", false, "LASTNAME");
        public final static Property PrimaryEmail = new Property(3, String.class, "primaryEmail", false, "PRIMARY_EMAIL");
        public final static Property UserpicFilename = new Property(4, String.class, "userpicFilename", false, "USERPIC_FILENAME");
        public final static Property LastLogin = new Property(5, String.class, "lastLogin", false, "LAST_LOGIN");
        public final static Property JoinedSince = new Property(6, String.class, "joinedSince", false, "JOINED_SINCE");
        public final static Property Created = new Property(7, String.class, "created", false, "CREATED");
    };

    private DaoSession daoSession;


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"user\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FIRSTNAME\" TEXT," + // 1: firstname
                "\"LASTNAME\" TEXT," + // 2: lastname
                "\"PRIMARY_EMAIL\" TEXT NOT NULL ," + // 3: primaryEmail
                "\"USERPIC_FILENAME\" TEXT," + // 4: userpicFilename
                "\"LAST_LOGIN\" TEXT," + // 5: lastLogin
                "\"JOINED_SINCE\" TEXT," + // 6: joinedSince
                "\"CREATED\" TEXT NOT NULL );"); // 7: created
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_user__id ON user" +
                " (\"_id\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"user\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String firstname = entity.getFirstname();
        if (firstname != null) {
            stmt.bindString(2, firstname);
        }
 
        String lastname = entity.getLastname();
        if (lastname != null) {
            stmt.bindString(3, lastname);
        }
        stmt.bindString(4, entity.getPrimaryEmail());
 
        String userpicFilename = entity.getUserpicFilename();
        if (userpicFilename != null) {
            stmt.bindString(5, userpicFilename);
        }
 
        String lastLogin = entity.getLastLogin();
        if (lastLogin != null) {
            stmt.bindString(6, lastLogin);
        }
 
        String joinedSince = entity.getJoinedSince();
        if (joinedSince != null) {
            stmt.bindString(7, joinedSince);
        }
        stmt.bindString(8, entity.getCreated());
    }

    @Override
    protected void attachEntity(User entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // firstname
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lastname
            cursor.getString(offset + 3), // primaryEmail
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // userpicFilename
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // lastLogin
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // joinedSince
            cursor.getString(offset + 7) // created
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFirstname(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLastname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPrimaryEmail(cursor.getString(offset + 3));
        entity.setUserpicFilename(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLastLogin(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setJoinedSince(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCreated(cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
