package de.tudarmstadt.informatik.tk.android.assistance.sdk.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "gyroscope_sensor".
 */
public class DbGyroscopeSensor implements de.tudarmstadt.informatik.tk.android.assistance.sdk.interfaces.IDbSensor {

    private Long id;
    private Double x;
    private Double y;
    private Double z;
    /** Not-null value. */
    private String created;
    private Integer accuracy;
    private Float xUncalibratedNoDrift;
    private Float yUncalibratedNoDrift;
    private Float zUncalibratedNoDrift;
    private Float xUncalibratedEstimatedDrift;
    private Float yUncalibratedEstimatedDrift;
    private Float zUncalibratedEstimatedDrift;

    public DbGyroscopeSensor() {
    }

    public DbGyroscopeSensor(Long id) {
        this.id = id;
    }

    public DbGyroscopeSensor(Long id, Double x, Double y, Double z, String created, Integer accuracy, Float xUncalibratedNoDrift, Float yUncalibratedNoDrift, Float zUncalibratedNoDrift, Float xUncalibratedEstimatedDrift, Float yUncalibratedEstimatedDrift, Float zUncalibratedEstimatedDrift) {
        this.id = id;
        this.x = x;
        this.y = y;
        this.z = z;
        this.created = created;
        this.accuracy = accuracy;
        this.xUncalibratedNoDrift = xUncalibratedNoDrift;
        this.yUncalibratedNoDrift = yUncalibratedNoDrift;
        this.zUncalibratedNoDrift = zUncalibratedNoDrift;
        this.xUncalibratedEstimatedDrift = xUncalibratedEstimatedDrift;
        this.yUncalibratedEstimatedDrift = yUncalibratedEstimatedDrift;
        this.zUncalibratedEstimatedDrift = zUncalibratedEstimatedDrift;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getX() {
        return x;
    }

    public void setX(Double x) {
        this.x = x;
    }

    public Double getY() {
        return y;
    }

    public void setY(Double y) {
        this.y = y;
    }

    public Double getZ() {
        return z;
    }

    public void setZ(Double z) {
        this.z = z;
    }

    /** Not-null value. */
    public String getCreated() {
        return created;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated(String created) {
        this.created = created;
    }

    public Integer getAccuracy() {
        return accuracy;
    }

    public void setAccuracy(Integer accuracy) {
        this.accuracy = accuracy;
    }

    public Float getXUncalibratedNoDrift() {
        return xUncalibratedNoDrift;
    }

    public void setXUncalibratedNoDrift(Float xUncalibratedNoDrift) {
        this.xUncalibratedNoDrift = xUncalibratedNoDrift;
    }

    public Float getYUncalibratedNoDrift() {
        return yUncalibratedNoDrift;
    }

    public void setYUncalibratedNoDrift(Float yUncalibratedNoDrift) {
        this.yUncalibratedNoDrift = yUncalibratedNoDrift;
    }

    public Float getZUncalibratedNoDrift() {
        return zUncalibratedNoDrift;
    }

    public void setZUncalibratedNoDrift(Float zUncalibratedNoDrift) {
        this.zUncalibratedNoDrift = zUncalibratedNoDrift;
    }

    public Float getXUncalibratedEstimatedDrift() {
        return xUncalibratedEstimatedDrift;
    }

    public void setXUncalibratedEstimatedDrift(Float xUncalibratedEstimatedDrift) {
        this.xUncalibratedEstimatedDrift = xUncalibratedEstimatedDrift;
    }

    public Float getYUncalibratedEstimatedDrift() {
        return yUncalibratedEstimatedDrift;
    }

    public void setYUncalibratedEstimatedDrift(Float yUncalibratedEstimatedDrift) {
        this.yUncalibratedEstimatedDrift = yUncalibratedEstimatedDrift;
    }

    public Float getZUncalibratedEstimatedDrift() {
        return zUncalibratedEstimatedDrift;
    }

    public void setZUncalibratedEstimatedDrift(Float zUncalibratedEstimatedDrift) {
        this.zUncalibratedEstimatedDrift = zUncalibratedEstimatedDrift;
    }

}
