package de.tudarmstadt.informatik.tk.android.assistance.sdk.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.tudarmstadt.informatik.tk.android.assistance.sdk.db.DbMobileConnectionSensor;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "mobile_connection_sensor".
*/
public class DbMobileConnectionSensorDao extends AbstractDao<DbMobileConnectionSensor, Long> {

    public static final String TABLENAME = "mobile_connection_sensor";

    /**
     * Properties of entity DbMobileConnectionSensor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CarrierName = new Property(1, String.class, "carrierName", false, "CARRIER_NAME");
        public final static Property MobileCountryCode = new Property(2, String.class, "mobileCountryCode", false, "MOBILE_COUNTRY_CODE");
        public final static Property MobileNetworkCode = new Property(3, String.class, "mobileNetworkCode", false, "MOBILE_NETWORK_CODE");
        public final static Property Created = new Property(4, String.class, "created", false, "CREATED");
        public final static Property VoipAvailable = new Property(5, Boolean.class, "voipAvailable", false, "VOIP_AVAILABLE");
    };


    public DbMobileConnectionSensorDao(DaoConfig config) {
        super(config);
    }
    
    public DbMobileConnectionSensorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"mobile_connection_sensor\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CARRIER_NAME\" TEXT," + // 1: carrierName
                "\"MOBILE_COUNTRY_CODE\" TEXT," + // 2: mobileCountryCode
                "\"MOBILE_NETWORK_CODE\" TEXT," + // 3: mobileNetworkCode
                "\"CREATED\" TEXT NOT NULL ," + // 4: created
                "\"VOIP_AVAILABLE\" INTEGER);"); // 5: voipAvailable
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_mobile_connection_sensor__id ON mobile_connection_sensor" +
                " (\"_id\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"mobile_connection_sensor\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbMobileConnectionSensor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String carrierName = entity.getCarrierName();
        if (carrierName != null) {
            stmt.bindString(2, carrierName);
        }
 
        String mobileCountryCode = entity.getMobileCountryCode();
        if (mobileCountryCode != null) {
            stmt.bindString(3, mobileCountryCode);
        }
 
        String mobileNetworkCode = entity.getMobileNetworkCode();
        if (mobileNetworkCode != null) {
            stmt.bindString(4, mobileNetworkCode);
        }
        stmt.bindString(5, entity.getCreated());
 
        Boolean voipAvailable = entity.getVoipAvailable();
        if (voipAvailable != null) {
            stmt.bindLong(6, voipAvailable ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbMobileConnectionSensor readEntity(Cursor cursor, int offset) {
        DbMobileConnectionSensor entity = new DbMobileConnectionSensor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // carrierName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mobileCountryCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mobileNetworkCode
            cursor.getString(offset + 4), // created
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // voipAvailable
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbMobileConnectionSensor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCarrierName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMobileCountryCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMobileNetworkCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCreated(cursor.getString(offset + 4));
        entity.setVoipAvailable(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbMobileConnectionSensor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbMobileConnectionSensor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
