package de.tudarmstadt.informatik.tk.android.assistance.sdk.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import de.tudarmstadt.informatik.tk.android.assistance.sdk.db.DbModuleAllowedCapabilities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "module_allowed_capabilities".
*/
public class DbModuleAllowedCapabilitiesDao extends AbstractDao<DbModuleAllowedCapabilities, Long> {

    public static final String TABLENAME = "module_allowed_capabilities";

    /**
     * Properties of entity DbModuleAllowedCapabilities.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, String.class, "type", false, "TYPE");
        public final static Property IsAllowed = new Property(2, boolean.class, "isAllowed", false, "IS_ALLOWED");
        public final static Property Created = new Property(3, String.class, "created", false, "CREATED");
        public final static Property UserId = new Property(4, Long.class, "userId", false, "USER_ID");
    };

    private DaoSession daoSession;

    private Query<DbModuleAllowedCapabilities> dbUser_DbModuleAllowedCapabilitiesListQuery;

    public DbModuleAllowedCapabilitiesDao(DaoConfig config) {
        super(config);
    }
    
    public DbModuleAllowedCapabilitiesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"module_allowed_capabilities\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TYPE\" TEXT NOT NULL ," + // 1: type
                "\"IS_ALLOWED\" INTEGER NOT NULL ," + // 2: isAllowed
                "\"CREATED\" TEXT NOT NULL ," + // 3: created
                "\"USER_ID\" INTEGER);"); // 4: userId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_module_allowed_capabilities__id ON module_allowed_capabilities" +
                " (\"_id\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_module_allowed_capabilities_TYPE ON module_allowed_capabilities" +
                " (\"TYPE\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_module_allowed_capabilities_IS_ALLOWED ON module_allowed_capabilities" +
                " (\"IS_ALLOWED\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_module_allowed_capabilities_USER_ID ON module_allowed_capabilities" +
                " (\"USER_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"module_allowed_capabilities\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbModuleAllowedCapabilities entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getType());
        stmt.bindLong(3, entity.getIsAllowed() ? 1L: 0L);
        stmt.bindString(4, entity.getCreated());
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(5, userId);
        }
    }

    @Override
    protected void attachEntity(DbModuleAllowedCapabilities entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbModuleAllowedCapabilities readEntity(Cursor cursor, int offset) {
        DbModuleAllowedCapabilities entity = new DbModuleAllowedCapabilities( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // type
            cursor.getShort(offset + 2) != 0, // isAllowed
            cursor.getString(offset + 3), // created
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // userId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbModuleAllowedCapabilities entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.getString(offset + 1));
        entity.setIsAllowed(cursor.getShort(offset + 2) != 0);
        entity.setCreated(cursor.getString(offset + 3));
        entity.setUserId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbModuleAllowedCapabilities entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbModuleAllowedCapabilities entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dbModuleAllowedCapabilitiesList" to-many relationship of DbUser. */
    public List<DbModuleAllowedCapabilities> _queryDbUser_DbModuleAllowedCapabilitiesList(Long userId) {
        synchronized (this) {
            if (dbUser_DbModuleAllowedCapabilitiesListQuery == null) {
                QueryBuilder<DbModuleAllowedCapabilities> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserId.eq(null));
                dbUser_DbModuleAllowedCapabilitiesListQuery = queryBuilder.build();
            }
        }
        Query<DbModuleAllowedCapabilities> query = dbUser_DbModuleAllowedCapabilitiesListQuery.forCurrentThread();
        query.setParameter(0, userId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbUserDao().getAllColumns());
            builder.append(" FROM module_allowed_capabilities T");
            builder.append(" LEFT JOIN user T0 ON T.\"USER_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbModuleAllowedCapabilities loadCurrentDeep(Cursor cursor, boolean lock) {
        DbModuleAllowedCapabilities entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbUser dbUser = loadCurrentOther(daoSession.getDbUserDao(), cursor, offset);
        entity.setDbUser(dbUser);

        return entity;    
    }

    public DbModuleAllowedCapabilities loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbModuleAllowedCapabilities> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbModuleAllowedCapabilities> list = new ArrayList<DbModuleAllowedCapabilities>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbModuleAllowedCapabilities> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbModuleAllowedCapabilities> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
