package de.tudarmstadt.informatik.tk.android.assistance.sdk.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "power_state_event".
 */
public class DbPowerStateEvent implements de.tudarmstadt.informatik.tk.android.assistance.sdk.interfaces.IDbSensor {

    private Long id;
    private Boolean isCharging;
    private Float percent;
    /** Not-null value. */
    private String created;
    private Integer chargingState;
    private Integer chargingMode;
    private Boolean powerSaveMode;

    public DbPowerStateEvent() {
    }

    public DbPowerStateEvent(Long id) {
        this.id = id;
    }

    public DbPowerStateEvent(Long id, Boolean isCharging, Float percent, String created, Integer chargingState, Integer chargingMode, Boolean powerSaveMode) {
        this.id = id;
        this.isCharging = isCharging;
        this.percent = percent;
        this.created = created;
        this.chargingState = chargingState;
        this.chargingMode = chargingMode;
        this.powerSaveMode = powerSaveMode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsCharging() {
        return isCharging;
    }

    public void setIsCharging(Boolean isCharging) {
        this.isCharging = isCharging;
    }

    public Float getPercent() {
        return percent;
    }

    public void setPercent(Float percent) {
        this.percent = percent;
    }

    /** Not-null value. */
    public String getCreated() {
        return created;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated(String created) {
        this.created = created;
    }

    public Integer getChargingState() {
        return chargingState;
    }

    public void setChargingState(Integer chargingState) {
        this.chargingState = chargingState;
    }

    public Integer getChargingMode() {
        return chargingMode;
    }

    public void setChargingMode(Integer chargingMode) {
        this.chargingMode = chargingMode;
    }

    public Boolean getPowerSaveMode() {
        return powerSaveMode;
    }

    public void setPowerSaveMode(Boolean powerSaveMode) {
        this.powerSaveMode = powerSaveMode;
    }

}
