package de.tudarmstadt.informatik.tk.kraken.android.sdk.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.tudarmstadt.informatik.tk.kraken.android.sdk.db.SensorContact;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SENSOR_CONTACT.
*/
public class SensorContactDao extends AbstractDao<SensorContact, Long> {

    public static final String TABLENAME = "SENSOR_CONTACT";

    /**
     * Properties of entity SensorContact.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ContactId = new Property(1, Long.class, "contactId", false, "CONTACT_ID");
        public final static Property GlobalContactId = new Property(2, Long.class, "globalContactId", false, "GLOBAL_CONTACT_ID");
        public final static Property DisplayName = new Property(3, String.class, "displayName", false, "DISPLAY_NAME");
        public final static Property GivenName = new Property(4, String.class, "givenName", false, "GIVEN_NAME");
        public final static Property FamilyName = new Property(5, String.class, "familyName", false, "FAMILY_NAME");
        public final static Property Starred = new Property(6, Integer.class, "starred", false, "STARRED");
        public final static Property LastTimeContacted = new Property(7, Integer.class, "lastTimeContacted", false, "LAST_TIME_CONTACTED");
        public final static Property TimesContacted = new Property(8, Integer.class, "timesContacted", false, "TIMES_CONTACTED");
        public final static Property Note = new Property(9, String.class, "note", false, "NOTE");
        public final static Property Timestamp = new Property(10, Long.class, "timestamp", false, "TIMESTAMP");
        public final static Property IsNew = new Property(11, Boolean.class, "isNew", false, "IS_NEW");
        public final static Property IsUpdated = new Property(12, Boolean.class, "isUpdated", false, "IS_UPDATED");
        public final static Property IsDeleted = new Property(13, Boolean.class, "isDeleted", false, "IS_DELETED");
    };

    private DaoSession daoSession;


    public SensorContactDao(DaoConfig config) {
        super(config);
    }
    
    public SensorContactDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SENSOR_CONTACT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CONTACT_ID' INTEGER," + // 1: contactId
                "'GLOBAL_CONTACT_ID' INTEGER," + // 2: globalContactId
                "'DISPLAY_NAME' TEXT," + // 3: displayName
                "'GIVEN_NAME' TEXT," + // 4: givenName
                "'FAMILY_NAME' TEXT," + // 5: familyName
                "'STARRED' INTEGER," + // 6: starred
                "'LAST_TIME_CONTACTED' INTEGER," + // 7: lastTimeContacted
                "'TIMES_CONTACTED' INTEGER," + // 8: timesContacted
                "'NOTE' TEXT," + // 9: note
                "'TIMESTAMP' INTEGER," + // 10: timestamp
                "'IS_NEW' INTEGER," + // 11: isNew
                "'IS_UPDATED' INTEGER," + // 12: isUpdated
                "'IS_DELETED' INTEGER);"); // 13: isDeleted
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SENSOR_CONTACT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SensorContact entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long contactId = entity.getContactId();
        if (contactId != null) {
            stmt.bindLong(2, contactId);
        }
 
        Long globalContactId = entity.getGlobalContactId();
        if (globalContactId != null) {
            stmt.bindLong(3, globalContactId);
        }
 
        String displayName = entity.getDisplayName();
        if (displayName != null) {
            stmt.bindString(4, displayName);
        }
 
        String givenName = entity.getGivenName();
        if (givenName != null) {
            stmt.bindString(5, givenName);
        }
 
        String familyName = entity.getFamilyName();
        if (familyName != null) {
            stmt.bindString(6, familyName);
        }
 
        Integer starred = entity.getStarred();
        if (starred != null) {
            stmt.bindLong(7, starred);
        }
 
        Integer lastTimeContacted = entity.getLastTimeContacted();
        if (lastTimeContacted != null) {
            stmt.bindLong(8, lastTimeContacted);
        }
 
        Integer timesContacted = entity.getTimesContacted();
        if (timesContacted != null) {
            stmt.bindLong(9, timesContacted);
        }
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(10, note);
        }
 
        Long timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(11, timestamp);
        }
 
        Boolean isNew = entity.getIsNew();
        if (isNew != null) {
            stmt.bindLong(12, isNew ? 1l: 0l);
        }
 
        Boolean isUpdated = entity.getIsUpdated();
        if (isUpdated != null) {
            stmt.bindLong(13, isUpdated ? 1l: 0l);
        }
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(14, isDeleted ? 1l: 0l);
        }
    }

    @Override
    protected void attachEntity(SensorContact entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SensorContact readEntity(Cursor cursor, int offset) {
        SensorContact entity = new SensorContact( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // contactId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // globalContactId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // displayName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // givenName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // familyName
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // starred
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // lastTimeContacted
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // timesContacted
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // note
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // timestamp
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0, // isNew
            cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0, // isUpdated
            cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0 // isDeleted
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SensorContact entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContactId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setGlobalContactId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setDisplayName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGivenName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFamilyName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStarred(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setLastTimeContacted(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setTimesContacted(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setNote(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTimestamp(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setIsNew(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0);
        entity.setIsUpdated(cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0);
        entity.setIsDeleted(cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SensorContact entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SensorContact entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
