package de.tudarmstadt.informatik.tk.assistance.sdk.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "running_tasks_sensor".
 */
public class DbRunningTasksSensor implements de.tudarmstadt.informatik.tk.assistance.sdk.interfaces.IDbSensor {

    private Long id;
    private String name;
    private Integer stackPosition;
    /** Not-null value. */
    private String created;

    public DbRunningTasksSensor() {
    }

    public DbRunningTasksSensor(Long id) {
        this.id = id;
    }

    public DbRunningTasksSensor(Long id, String name, Integer stackPosition, String created) {
        this.id = id;
        this.name = name;
        this.stackPosition = stackPosition;
        this.created = created;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStackPosition() {
        return stackPosition;
    }

    public void setStackPosition(Integer stackPosition) {
        this.stackPosition = stackPosition;
    }

    /** Not-null value. */
    public String getCreated() {
        return created;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated(String created) {
        this.created = created;
    }

}
